services:
  - type: web
    name: ajcarcare-backend
    runtime: node
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /tmp/puppeteer
